"""init machine_v2

Revision ID: 6724c253cce4
Revises: 
Create Date: 2025-08-20 23:20:43.192080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6724c253cce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numberplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('date_in', sa.DateTime(), nullable=True),
    sa.Column('date_out', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numberplate')
    # ### end Alembic commands ###
